### PR TITLE
in HttpClientOptions changed the AssertValid if condition  

### PR DESCRIPTION
**Pull request by AWasseem**
(string.IsNullOrWhiteSpace(HttpClientName) || HttpClient == null)

insetead of
if ((string.IsNullOrWhiteSpace(HttpClientName) && HttpClient == null) ||
    (!string.IsNullOrWhiteSpace(HttpClientName) && HttpClient != null))

### CODE REVIEW

**Comment by lahma** [comment]
I don't this change is correct, the original code does what it is supposed to.

**Comment by AWasseem** [comment]
try to initialize HttpClient like this despite of filling HttpClient and HttpClientName it will throw exception **Either http client name or http client instance required**
```
builder.Services.AddQuartzHttpClient(e => {
    e.HttpClient = new HttpClient
    {
        BaseAddress = new Uri("http://localhost:5000/quartz-api/"),
        DefaultRequestHeaders = { { "X-Quartz-ApiKey", "MySuperSecretApiKey" } }
    };
    e.SchedulerName = "HRMSScheduler";
    e.HttpClientName = "HRMSSchedulerHttpClient";
});
```

**Comment by jafin** [comment]
Is the error message to ambiguous?  Maybe separating to be more clear about both error scenarios?
```c#
  if (string.IsNullOrWhiteSpace(HttpClientName) && HttpClient == null) 
        {
            throw new InvalidOperationException("Either http client name or http client instance required");
        }
        
        if (!string.IsNullOrWhiteSpace(HttpClientName) && HttpClient != null)
        {
            throw new InvalidOperationException("You have set both an HttpClientName and an HttpClient instance. Please specify only one.");
        }
```

**Comment by lahma** [comment]
Maybe improving the error reporting is a good option.

**Pull request closed without merging**
