### PR TITLE
Adding support for Memory Optimized Tables in SQL Server 2014 RTM, 2016 RTM, and 2016 SP1 or later

### PR DESCRIPTION
**Pull request by JBVyncent**
Memory Optimized tables are supported in Developer, Enterprise and Evaluation editions of 64-Bit versions of SQL Server 2014 RTM and SQL Server 2016 RTM. Memory Optimized tables are also supported in any edition of SQL Server 2016 SP1 or later.

Moving the QRTZ_LOCKS table from standard, disk-based tables to memory optimized tables could result in substantial performance increase writing to the QRTZ_LOCKS table. While there are several ways to accomplish this code, the solution proposed here results in the bare minimum of source code changes.

Essentially, the steps are as follows:

   1. Modify the existing database to add a new FILESTREAM filegroup and Memory Optimized table for QRTZ_LOCKS (example in "tables_sqlServerMOT.sql" script) 
   2. Added the class "UpdateRowLockSemaphoreMOT.cs" to address the way QuartzScheduler handles locking versus the lack of locking available in memory optimized tables (https://msdn.microsoft.com/en-us/library/dn133169.aspx). This also allows for the possibility of specifying "quartz.jobStore.lockHandler.type = Quartz.Impl.AdoJobStore.UpdateRowLockSemaphoreMOT, Quartz" in the quartz.config file.

### CODE REVIEW

**Comment by lahma** [comment]
Thanks for taking the time to bring this idea to our attention. It seems however, that there are only commits that already exist in the code base? It seems that the actual additions are not part of the pull request (like the file UpdateRowLockSemaphoreMOT.cs you mentioned). Could you please double check your PR?

**Comment by JBVyncent** [comment]
Good Day Sir,

Apologies for the oversight. In my rush to post the idea before a meeting,
I made a multitude of mistakes.

QuartzScheduler is an amazing product!

Regards,
John-Brian Vyncent

**Comment by lahma** [comment]
I have cherry-picked you commit and cleaned it a bit, will be part of beta 1. I had some trouble running smoke tests against dockerized SQL Server. As I'm no expert using memory-optimized tables, I hope people have time to test this out and find possible.

**Comment by JBVyncent** [comment]
Good Morning Sir,

I am honored that you have considered my contribution worthy of inclusion
in your magnificent program. Thank you!

We are only now beginning our exploration of SQL Server 2017, and
separately, dockerized SQL as well, so I hope to have some feedback on that
configuration in the coming weeks.


Regards,
John-Brian Vyncent

**Pull request closed without merging**
