### PR TITLE
[SPIKE] Task based API spike for job worker pool

### PR DESCRIPTION
**Pull request by danielmarbach**
* Switched to .NET 4.6.1 to have support for `TaskCreationOptions.RunContinuationsAsynchronously` (see bug in 4.6 https://github.com/dotnet/coreclr/issues/2021)
* Implemented `AsyncManualResetEvent` for pause support
* Introduced really dumb version `IJobWorkerPool`

### CODE REVIEW

**Comment by danielmarbach** [comment]
@lahma this is far from complete, but as you can see by using async primitives we can get rid of some locking and field state toggling. We can also get rid of Monitor.Wait and Pulse and switch completely block free code. 

Furthermore we could also float the cancellation token into the job worker pool. We could even think about floating it over the worker pool into the `JobRunShell.Run` method by changing the signature of `Run` on the worker pool to something like `Run(Func<CancellationToken, Task> runnable, CancellationToken token = default(CancellationToken))`

**Comment by lahma** [comment]
Based on the discussion of the bug it seems that even 4.6.1 does not fix it?

> unfortunately this was discovered too late for 4.6.1 but it will be in the next update. But it will be on coreclr before that.

Target frameworks might be a good candidate for a Gitter chat, tried to decipher alternatives last night and no fun.

**Comment by lahma** [comment]
Thanks, looks promising!

**Comment by danielmarbach** [comment]
@lahma why did you merge this??? Far from done and I haven't implemented the `Set` and `Reset` of the manual reset event yet. So this is super buggy right now. I suggest you revert

**Comment by danielmarbach** [comment]
The idea of this PR was more to explore alternatives and drive the implementation to a point where we can say: That works and then reimplement the necessary changes on a clean slate

**Comment by lahma** [comment]
I have reverted it now. Merged the PR as you didn't state that it shouldn't be pulled in.

**Comment by danielmarbach** [comment]
@lahma 

> this is far from complete
https://github.com/quartznet/quartznet/pull/367#issuecomment-219866867

Sorry I thought it was clear. In other OSS projects we use conventions like [SPIKE] or [WIP] to indicate that a PR should not be merged and is either a thought experiment or work in progress.

**Comment by danielmarbach** [comment]
Can you reopen this PR? It seems I can't without sending in a new one

**Comment by lahma** [comment]
Sorry, there seems to be no option to reopen a PR that has been once merged.

**Pull request merged**
