### PR TITLE
Lazy initialize some properties of JobExecutionContextImpl

### PR DESCRIPTION
**Pull request by drieseng**
Lazy initialize cancellationTokenSource, cancellationToken, data and jobDataMap.
This has quite a positive impact on both performance and memory allocations.

**To be discussed:**
* Does this lazy init have to be threadsafe?
  If it is, we'll need to introduce a lock field.
* Is it correct to lazy init **jobDataMap**?
  I think it's not, because I assume we want the "state" of both the job and trigger data at the time we create the **JobExecutionContextImpl**.

<details>
<summary>Benchmark results</summary>

|                                                       Method | Branch |    Mean |     Error |    StdDev |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------------------------------------------------------- |-------:|--------:|----------:|----------:|-------:|-------:|-------:|----------:|
| Concurrent_MaxThreads_30Jobs_30TriggersPerJob_MaxBatchSize30 | main   |8.379 us | 0.1643 us | 0.1956 us | 0.5780 | 0.2480 | 0.0860 |    3.1 KB |
| Concurrent_MaxThreads_30Jobs_30TriggersPerJob_MaxBatchSize30 | PR     |7.206 us | 0.1417 us | 0.1687 us | 0.4520 | 0.1820 | 0.0700 |   2.42 KB |
</details>

### CODE REVIEW

**Comment by lahma** [comment]
Threading shouldn't be an issue, but like you've said, we might be capturing a different state depending on when it's done. I'm not quite sure about this change.

**Comment by drieseng** [comment]
I propose not to take the lazy init of jobDataMap then, I'll search for another way to accelerate that part.
I'll update the PR later this week. I'm working on boosting our threadpool right now.

**Comment by drieseng** [comment]
@lahma I had a closer look at this, and lazily constructing the (merged) **JobDataMap** is fine after all. Both the job detail and the trigger are actually clones of their "operational" instances, so they cannot be modified by other "runs".

I did decide to make the lazy init thread safe after all. Those 32 bytes extra are well justified here.

<details>
<summary>Benchmark results</summary>

|                                         Method | Branch |    Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------------------- |--------|--------:|---------:|---------:|-------:|------:|------:|----------:|
|       Ctor_JobDataMapEmpty_TriggerDataMapEmpty | master |123.3 ns | 1.50 ns  |  1.33 ns | 0.1452 |     - |     - |     608 B |
|       Ctor_JobDataMapEmpty_TriggerDataMapEmpty | PR     |31.97 ns | 0.340 ns | 0.284 ns | 0.0573 |     - |     - |     240 B |
|    Ctor_JobDataMapEmpty_TriggerDataMapNotEmpty | master |230.9 ns | 2.60 ns  |  2.43 ns | 0.1779 |     - |     - |     744 B |
|    Ctor_JobDataMapEmpty_TriggerDataMapNotEmpty | PR     |31.10 ns | 0.293 ns | 0.274 ns | 0.0573 |     - |     - |     240 B |
|    Ctor_JobDataMapNotEmpty_TriggerDataMapEmpty | master |235.6 ns | 1.87 ns  |  1.75 ns | 0.1779 |     - |     - |     744 B |
|    Ctor_JobDataMapNotEmpty_TriggerDataMapEmpty | PR     |31.00 ns | 0.227 ns | 0.201 ns | 0.0573 |     - |     - |     240 B |
| Ctor_JobDataMapNotEmpty_TriggerDataMapNotEmpty | master |305.7 ns | 3.24 ns  |  2.71 ns | 0.2046 |     - |     - |     856 B |
| Ctor_JobDataMapNotEmpty_TriggerDataMapNotEmpty | PR     |30.73 ns | 0.169 ns | 0.132 ns | 0.0573 |     - |     - |     240 B |

</details>

**Comment by lahma** [comment]
Thank you.

**Pull request merged**
