### PR TITLE
Allow PersistJobDataAfterExecution and ConcurrentExecutionDisallowed to be explicitly in JobBuilder and pulled up to IJobConfigurator

### PR DESCRIPTION
**Pull request by saklig**
Cherry picked commits for exposing DisallowConcurrentExecution and PersistJobDataAfterExecution in IJobConfigurator, and dependent changes made to the JobBuilder and JobDetailImpl.
I see there is some changes to setters, from public to private, which might qualify as a breaking change in 3.x. In that case I will walk those changes back in a new commit to avoid breaking.

### CODE REVIEW

**Comment by lahma** [comment]
@drieseng thoughts on having these on v3 as 3.5 release or similar? This is binary breaking change but I don't think we transfer job details on the wire.

**Comment by drieseng** [comment]
@lahma I think this is safe to go into a 3.x release.

**Comment by lahma** [comment]
Thanks for assessing this impact @drieseng !

**Comment by lahma** [comment]
Thanks for the PR @saklig !

**Comment by saklig** [comment]
@lahma Thanks for accepting it!

**Pull request merged**
