### PR TITLE
Make IJob async only

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to #331 

Removes `IAsyncJob` and makes `IJob` async only

I synchronous version of a job is super simple by doing:

```
class MySyncJob : IJob {
   public Task Execute(...) {
      return Task.FromResult(0); // or Task.CompletedTask for 4.6
  }
}
```

When #335 and #338 ar merged I will rebase and force push

### CODE REVIEW

**Comment by danielmarbach** [comment]
Still catching up with the tests and their structure. Please bear with me

**Comment by lahma** [comment]
Sure, no worries. I'm trying to get the project.json structure to work without csproj references, will inform when pushed.

**Comment by lahma** [comment]
This looks good, after rebase probably ready to be pulled in. The IJob/IAsyncJob was truly a crutch and it was probably a bad decision to support both when starting the conversion.

**Comment by danielmarbach** [comment]
Was on vacation. Will rebase next week

**Comment by danielmarbach** [comment]
Rebased and force pushed

**Comment by danielmarbach** [comment]
Build seems to fail with

> Specify which project or solution file to use because the folder contains more than one project or solution file.

**Comment by lahma** [comment]
Thank you for tweaking the commit, don't mind about the appveyor messages for now as I'm going to remake the build scripts anyway. Thanks for this change!

**Pull request merged**
