### PR TITLE
Implemented wait time between retries for AquireNextTriggers after fail

### PR DESCRIPTION
**Pull request by monkey-mku**
Fix for issue #428

### CODE REVIEW

**Comment by KoosBusters** [comment]
Could this be merged? 
Would benefit overall stability by not wasting a complete logical processor of the system on database retries.

**Comment by AntonSemenovKazan** [comment]
I need this fix too.
I need all levels of log.
Or my log blows up without connection.

Thnx a lot =)

Please, merge in 2.x

**Comment by patagonaa** [comment]
Please merge this, hogging a whole CPU Core for logging and retrying because the DB is not reachable is insane...

**Comment by Fijo** [comment]
+1 Make Quartz viable for enterprise usecases w/o tearing servers apart!

**Pull request merged**
