### PR TITLE
Resolve build error

### PR DESCRIPTION
**Pull request by chilin**
Upgrade odp.net.managed from 121.1.1 to 121.1.2

### CODE REVIEW

**Comment by mj1856** [comment]
I'm seeing the same thing.  121.1.1 has been removed from Nuget so this is essential in order to build.  Please merge.  Thanks.

**Comment by mj1856** [comment]
Also it looks like there's a reference in [Quartz.build](https://github.com/quartznet/quartznet/blob/d54171ba05b1876b2434f2c005689bfcbbe941b0/Quartz.build#L595) that needs to be updated.

Not sure if it matters or not.

**Comment by lahma** [comment]
Should probably replace the whole package with this official one I guess? 

https://www.nuget.org/packages/Oracle.ManagedDataAccess/

Now the PR addresses only version upgrade instead of package change.

**Comment by lahma** [comment]
There seems to be a another pull request that addresses the issue with correct package https://github.com/quartznet/quartznet/pull/328

**Comment by danielmarbach** [comment]
See also https://github.com/quartznet/quartznet/pull/338

**Comment by lahma** [comment]
I took in the  #338 with required alterations as it has the complete fix, including build file changes.

**Pull request closed without merging**
