### PR TITLE
fixes#411 - Added ability to detect deleted files and notify the listener

### PR DESCRIPTION
**Pull request by senthilkumarmohan**
Hi,

I have added the ability to detect the deleted files to dir scanner job. Added FilesDeleted method to the listener interface. I have implemented this by saving the current file list in the JobDataMap and comparing the list during the  next iteration. Please review and share your feedback - happy to implement any changes.

Thanks,
Senthil

### CODE REVIEW

**Comment by senthilkumarmohan** [comment]
Hi @lahma, could you please share your feedback on this PR?

**Comment by lahma** [comment]
Thanks for taking the time to prepare this change and sorry for the late reply. The change looks good, only thing is that it changes the API so probably cannot be included in a minor release.

**Comment by senthilkumarmohan** [comment]
Okay. Thanks for your response - leave it with you to decide on the version this can be merged into.

**Comment by lahma** [comment]
As this only affects Quartz.Jobs package it's lighter procedure in my book. I'll probably brand next release as 3.1 so it will show some things have changed. Thanks again!

**Pull request merged**
