### PR TITLE
Refactor UnitTests

### PR DESCRIPTION
**Pull request by jafin**
- Update Assertions to use constraint model ([Nunit 4 suggested approach](https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html))
  - i.e. `Assert.True` becomes `Assert.That( value, Is.True)`
  - `Assert.Equal` => `Assert.That(val, Is.EqualTo(expected)`
  - `Assert.IsNotNull` => `Assert.That(val, Is.Not.Null)`
  - etc
- Wrap multiple asserts inside [Assert.Multiple](https://docs.nunit.org/articles/nunit/writing-tests/assertions/multiple-asserts.html)
- Minor refactor on language optimizations (object initializer, empty braces) in test lib.
- Add FluentAssertions.Analyzer package
- Add NUnit.Analyzers to package
- Remove the global using Assert for ClassicAssert, no longer required.
- Add `[OneTimeTearDown]` to dispose of objects Nunit.Analyzer requested. (DisallowConcurrentJobExecutioNTests)

### CODE REVIEW

**Comment by lahma** [comment]
Wow, you really did bite the bullet with this one. Is this ready for review?

**Comment by jafin** [comment]
@lahma yes ready for review.

**Review by lahma — APPROVED** [review]
Great work here, a lot of grind required to improve these and thank you for taking the time. Ideally we would use FluentAssertions for everything, but that would be a huge undertaking.

**Comment by jafin** [comment]
> Ideally we would use FluentAssertions for everything, but that would be a huge undertaking.

Maybe next wet uneventful day I have free. 🥲

**Pull request merged**
