### PR TITLE
Fix error messaging to match error conditions in Quartz/CronExpression

### PR DESCRIPTION
**Pull request by KPDeweese**
While working with Quartznet I noticed that some of the error messaging did not seem to be consistent with the behavior I was observing, specifically I was receiving an error that my cron schedule for running every 24 hours was greater than the allowed increment of 24. I have created this pull request to bring the error messaging into alignment with the corresponding error conditions for both this piece of logic, and the similar piece restricting the maximum minute interval to 59.

### CODE REVIEW

**Review by lahma — APPROVED** [review]
Looks good, thank you!

**Comment by lahma** [comment]
But tests are failing, please take a look 😅

**Comment by KPDeweese** [comment]
Sorry, please disregard last update

**Comment by jafin** [comment]
@KPDeweese some suggestions
- revert the change to static, as the lib won't even compile.
- Update CronExpressionTest and amend the tests to match the change in Expected result now. The tests are still expecting the old value and need to match your change.

```text
Assert.That(e.Message, Is.EqualTo("Increment > 24 : 120"))
  String lengths are both 20. Strings differ at index 13.
  Expected: "Increment > 24 : 120"
  But was:  "Increment > 23 : 120"
  ------------------------^
```
There are other tests that are failing, (you can see from the runner logs ie https://github.com/quartznet/quartznet/actions/runs/10404703998/job/28814535388?pr=2521) but similar to the above will be the fix, (adjusting test expectation)
Are you able to run the unit tests locally? As that would provide a simple way to validate the change and make sure all tests pass before pushing the PR ?

**Comment by lahma** [comment]
Superseded by #2524  , ideally you should always create a new branch for pull requests, I didn't want to start pushing fixes to your `main` branch.

**Pull request closed without merging**
