### PR TITLE
Removed dbFailureRetryInterval since it is no longer used

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to #331 and #347

### CODE REVIEW

**Comment by lahma** [comment]
This seems to be a duplicate of 347? Removal of using NUnit.Framework at least looks wrong. Builds should now roll if you rebase against quartznet-3 branch. I made minimal patches there too, separate work going on creating new setup with FAKE.

**Comment by danielmarbach** [comment]
Not a duplicate. One is against master. Will check regarding NUnit

**Comment by danielmarbach** [comment]
Rebased, updated and pushed. Don't know how the nunit stuff got removed. Magic fingers ;)

**Comment by lahma** [comment]
Thank you!

**Pull request merged**
